#!/usr/bin/env python3

import argparse
import os
import re
import shutil
import time
from typing import Optional

parser = argparse.ArgumentParser()
parser.add_argument("time", nargs="?")
parser.add_argument("message", nargs="*")


def parse_time(t: Optional[str]) -> Optional[int]:
    if not t:
        return None
    mo = re.fullmatch(r"(?:(\d+)h)?(?:(\d+)m)?(?:(\d+)s)?(\d*)", t)
    if not mo:
        return None
    h, m, s, r = mo.groups()
    if r:
        if s:
            return None
        elif m:
            s = r
        elif h:
            m = r
        else:
            return int(r)
    return 3600 * int(h or 0) + 60 * int(m or 0) + int(s or 0)


def main():
    args = parser.parse_args()
    prog = shutil.which("notify-send")
    message = " ".join(args.message) or "Time's up!"
    t = parse_time(args.time)
    if t is None:
        parser.error("supply duration e.g. 1h30 or 8m45")
    if prog is None:
        raise SystemExit("notify-send is not installed")
    time.sleep(t)
    os.execl(prog, prog, message)


if __name__ == "__main__":
    main()
